# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API). 

    OpenAPI spec version: 1.0.12
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.statements_api import StatementsApi


class TestStatementsApi(unittest.TestCase):
    """ StatementsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.statements_api.StatementsApi()

    def tearDown(self):
        pass

    def test_get_statements(self):
        """
        Test case for get_statements

        
        """
        pass


if __name__ == '__main__':
    unittest.main()
