# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API). 

    OpenAPI spec version: 1.0.12
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import sys
import os
import re

# python 2 and python 3 compatibility library
from six import iteritems

from ..configuration import Configuration
from ..api_client import ApiClient


class StatementsApi(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        config = Configuration()
        if api_client:
            self.api_client = api_client
        else:
            if not config.api_client:
                config.api_client = ApiClient()
            self.api_client = config.api_client

    def get_statements(self, c, **kwargs):
        """
        Given a list of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts, retrieves a paged list of concept-relations where either the subject or object concept matches at least one concept in the input list 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_statements(c, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param list[str] c: set of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts to be used in a search for associated concept-relation statements  (required)
        :param int page_number: (1-based) number of the page to be returned in a paged set of query results 
        :param int page_size: number of concepts per page to be returned in a paged set of query results 
        :param str keywords: a (url-encoded, space-delimited) string of keywords or substrings against which to match the subject, predicate or object names of the set of concept-relations matched by any of the input exact matching concepts 
        :param str semgroups: a (url-encoded, space-delimited) string of semantic groups (specified as codes CHEM, GENE, ANAT, etc.) to which to constrain the subject or object concepts associated with the query seed concept (see [SemGroups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt) for the full list of codes) 
        :param list[str] beacons: set of IDs of beacons to be used as knowledge sources for the query 
        :param str session_id: identifier to be used for tagging session data 
        :return: list[Statement]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('callback'):
            return self.get_statements_with_http_info(c, **kwargs)
        else:
            (data) = self.get_statements_with_http_info(c, **kwargs)
            return data

    def get_statements_with_http_info(self, c, **kwargs):
        """
        Given a list of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts, retrieves a paged list of concept-relations where either the subject or object concept matches at least one concept in the input list 
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please define a `callback` function
        to be invoked when receiving the response.
        >>> def callback_function(response):
        >>>     pprint(response)
        >>>
        >>> thread = api.get_statements_with_http_info(c, callback=callback_function)

        :param callback function: The callback function
            for asynchronous request. (optional)
        :param list[str] c: set of [CURIE-encoded](https://www.w3.org/TR/curie/) identifiers of exactly matching concepts to be used in a search for associated concept-relation statements  (required)
        :param int page_number: (1-based) number of the page to be returned in a paged set of query results 
        :param int page_size: number of concepts per page to be returned in a paged set of query results 
        :param str keywords: a (url-encoded, space-delimited) string of keywords or substrings against which to match the subject, predicate or object names of the set of concept-relations matched by any of the input exact matching concepts 
        :param str semgroups: a (url-encoded, space-delimited) string of semantic groups (specified as codes CHEM, GENE, ANAT, etc.) to which to constrain the subject or object concepts associated with the query seed concept (see [SemGroups](https://metamap.nlm.nih.gov/Docs/SemGroups_2013.txt) for the full list of codes) 
        :param list[str] beacons: set of IDs of beacons to be used as knowledge sources for the query 
        :param str session_id: identifier to be used for tagging session data 
        :return: list[Statement]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['c', 'page_number', 'page_size', 'keywords', 'semgroups', 'beacons', 'session_id']
        all_params.append('callback')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_statements" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'c' is set
        if ('c' not in params) or (params['c'] is None):
            raise ValueError("Missing the required parameter `c` when calling `get_statements`")


        collection_formats = {}

        resource_path = '/statements'.replace('{format}', 'json')
        path_params = {}

        query_params = {}
        if 'c' in params:
            query_params['c'] = params['c']
            collection_formats['c'] = 'multi'
        if 'page_number' in params:
            query_params['pageNumber'] = params['page_number']
        if 'page_size' in params:
            query_params['pageSize'] = params['page_size']
        if 'keywords' in params:
            query_params['keywords'] = params['keywords']
        if 'semgroups' in params:
            query_params['semgroups'] = params['semgroups']
        if 'beacons' in params:
            query_params['beacons'] = params['beacons']
            collection_formats['beacons'] = 'multi'
        if 'session_id' in params:
            query_params['sessionId'] = params['session_id']

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.\
            select_header_accept(['application/json'])

        # Authentication setting
        auth_settings = []

        return self.api_client.call_api(resource_path, 'GET',
                                        path_params,
                                        query_params,
                                        header_params,
                                        body=body_params,
                                        post_params=form_params,
                                        files=local_var_files,
                                        response_type='list[Statement]',
                                        auth_settings=auth_settings,
                                        callback=params.get('callback'),
                                        _return_http_data_only=params.get('_return_http_data_only'),
                                        _preload_content=params.get('_preload_content', True),
                                        _request_timeout=params.get('_request_timeout'),
                                        collection_formats=collection_formats)
