# coding: utf-8

"""
    Translator Knowledge Beacon API

    This is the Translator Knowledge Beacon Aggregator web service application programming interface (API). 

    OpenAPI spec version: 1.0.12
    Contact: richard@starinformatics.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Summary(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, idmap=None, frequency=None):
        """
        Summary - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'idmap': 'str',
            'frequency': 'int'
        }

        self.attribute_map = {
            'id': 'id',
            'idmap': 'idmap',
            'frequency': 'frequency'
        }

        self._id = id
        self._idmap = idmap
        self._frequency = frequency

    @property
    def id(self):
        """
        Gets the id of this Summary.
        the type 

        :return: The id of this Summary.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this Summary.
        the type 

        :param id: The id of this Summary.
        :type: str
        """

        self._id = id

    @property
    def idmap(self):
        """
        Gets the idmap of this Summary.
        The URL to execute the exactmatches API call on the id

        :return: The idmap of this Summary.
        :rtype: str
        """
        return self._idmap

    @idmap.setter
    def idmap(self, idmap):
        """
        Sets the idmap of this Summary.
        The URL to execute the exactmatches API call on the id

        :param idmap: The idmap of this Summary.
        :type: str
        """

        self._idmap = idmap

    @property
    def frequency(self):
        """
        Gets the frequency of this Summary.
        the number of instances of the specified type 

        :return: The frequency of this Summary.
        :rtype: int
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """
        Sets the frequency of this Summary.
        the number of instances of the specified type 

        :param frequency: The frequency of this Summary.
        :type: int
        """

        self._frequency = frequency

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Summary):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
